<%@ Page Language="C#" AutoEventWireup="true" CodeFile="AreaData.aspx.cs" MasterPageFile="~/MasterPage.master" Inherits="Admin" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="Server">
    <script type="text/javascript">
        $(document).ready(function () {
            <%= (this.DetailsView1.DefaultMode== DetailsViewMode.ReadOnly ? "": " $('#myModal').modal();" )           
        %>
        })
    </script>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="Server">
    <asp:Button runat="server" ID="btnAddData" Text="新增" OnClick="btnAddData_Click" CssClass=" btn btn-primary" />
    顯示頁數<asp:DropDownList runat="server" ID="ddlPageNum" AutoPostBack="true"
        OnSelectedIndexChanged="ddlPageNum_SelectedIndexChanged">
    </asp:DropDownList>
    <asp:GridView ID="gvData" runat="server" AutoGenerateDeleteButton="True" CssClass="table table-hover"
        AutoGenerateSelectButton="True" OnRowDeleting="gvData_RowDeleting" OnSelectedIndexChanging="gvData_SelectedIndexChanging">
    </asp:GridView>
    <asp:Label runat="server" ID="lblResult"></asp:Label>

    <div id="myModal" class="modal fade" role="dialog">
        <div class="modal-dialog">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">土地資料</h4>
                </div>
                <div class="modal-body">
                    <asp:DetailsView ID="DetailsView1" runat="server" CssClass="table" AutoGenerateEditButton="True" Visible="false" OnModeChanging="DetailsView1_ModeChanging"
                        AutoGenerateRows="False" OnItemInserting="DetailsView1_ItemInserting" OnItemUpdating="DetailsView1_ItemUpdating">
                        <Fields>
                            <asp:BoundField DataField="地號" HeaderText="地號" />
                            <asp:BoundField DataField="地段號" HeaderText="地段號"  />
                            <asp:BoundField DataField="地段名稱" HeaderText="地段名稱"  />
                            <asp:BoundField DataField="所有者" HeaderText="所有者" />
                            <asp:BoundField DataField="行政區" HeaderText="行政區" Visible="false" />
                        </Fields>
                    </asp:DetailsView>

                    <div class="form" id="test" runat="server">
                        <div class="form-group">
                            <label for="email">行政區:</label>
                            <asp:DropDownList runat="server" ID="ddlArea" AutoPostBack="true" DataTextField="行政區名" DataValueField="ID"
                                OnSelectedIndexChanged="ddlArea_SelectedIndexChanged" CssClass="form-control">
                            </asp:DropDownList>
                        </div>
                        <div class="form-group">
                            <label for="pwd">地段:</label>
                            <asp:DropDownList runat="server" ID="ddlLot" AutoPostBack="true" DataTextField="地段名稱" DataValueField="地段號"
                                CssClass="form-control">
                            </asp:DropDownList>
                        </div>
                        <div class="form-group">
                            <label for="pwd">地號:</label>
                            <asp:TextBox runat="server" ID="txtArea" Text="" CssClass="form-control"></asp:TextBox>
                        </div>
                        <div class="form-group">
                            <label for="pwd">所有者:</label>
                            <asp:TextBox runat="server" ID="TextBox3" Text="" CssClass="form-control"></asp:TextBox>
                        </div>
                        <div class="form-group">
                            <asp:Button runat="server" ID="btnQuery" Text="確定" OnClick="btnQuery_Click" CssClass="form-control btn btn-primary"></asp:Button>
                        </div>
                    </div>

                </div>
            </div>

        </div>
    </div>
</asp:Content>
